# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GithubTestProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '10.0'
  use_frameworks!

  # Pods for GithubTestProject

  pod 'Alamofire', '~> 4.7'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'ObjectMapper', '~> 3.4'
  pod 'Kingfisher', '~> 4.0'
  pod 'IQKeyboardManagerSwift'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'

end
